root: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
env:
  node: true
  es2022: true
rules:
  # Add your custom rules here
  # For example:
  # '@typescript-eslint/no-explicit-any': 'warn'
  '@typescript-eslint/no-explicit-any': 'error'
  '@typescript-eslint/no-unsafe-argument': 'error'
  '@typescript-eslint/no-unsafe-assignment': 'error'
  '@typescript-eslint/no-unsafe-member-access': 'error'
  '@typescript-eslint/no-unsafe-return': 'error'
